### ISSUE TITLE
enqueue waypoints on front-page - AgencyPro

### ISSUE THREAD

**Issue by neilgee** [copyblogger/genesis-simple-share#53] opened 2015-06-26 03:35 UTC
Was getting a JS error on front page for Agency Pro
`Uncaught TypeError: $(...).waypoint is not a function`

Have to enqueue waypoints in front-page.php to fix
`wp_enqueue_script( 'genesis-simple-share-waypoint-js' );`

**Comment by neilgee** [comment] 2015-08-13 00:15
Actually the error will occur on anytheme's front page when you start to add posts into it using something like featured posts widget

**Comment by dreamwhisper** [comment] 2015-08-13 13:33
This is a duplicate of https://github.com/copyblogger/genesis-simple-share/issues/49 so will close.

**Closed by dreamwhisper** 2015-08-13 13:33 UTC
