### ISSUE TITLE
LinkedIn count no longer working

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-share#72] opened 2016-05-12 13:23 UTC
We have seen several reports of broken LinkedIn share buttons in Rainmaker support today. The LinkedIn button is not loading or displaying the count. Demo URLs:
- http://www.copyblogger.com/email-marketing-defined/ (and all Copyblogger posts)
- http://growprogram.com/snapchat-insurance-agents/
- http://nick-cernis.preview76.rmkr.net/blog/category-1/new-8-post/

The console shows a 400 (Bad Request) error against the LinkedIn count API URL:

https://www.linkedin.com/countserv/count/share?format=jsonp&url=http%3A%2F%2Fwww.copyblogger.com%2Femail-marketing-defined%2F&callback=jQuery111302880242855132005_1463058833340&_=1463058833341

Visiting that link shows an “invalid callback parameter” message. 
#### Findings so far
- LinkedIn's API seems to now reject callback parameters that contain numbers or punctuation.
  
  This request works (contains `&callback=abc`):
  
  https://www.linkedin.com/countserv/count/share?format=jsonp&url=http%3A%2F%2Fgrowprogram.com%2Fsnapchat-insurance-agents%2F&callback=abc
  
  But these return a 400 “bad request” response and show an “Invalid callback parameter” error (`&callback=123` or `&callback=abc123` or `&callback=a_b_c`):
  - https://www.linkedin.com/countserv/count/share?format=jsonp&url=http%3A%2F%2Fgrowprogram.com%2Fsnapchat-insurance-agents%2F&callback=123
  - https://www.linkedin.com/countserv/count/share?format=jsonp&url=http%3A%2F%2Fgrowprogram.com%2Fsnapchat-insurance-agents%2F&callback=abc123
  - https://www.linkedin.com/countserv/count/share?format=jsonp&url=http%3A%2F%2Fgrowprogram.com%2Fsnapchat-insurance-agents%2F&callback=a_b_c
- I couldn't find anything logged in the [Sharrre repo](https://github.com/Julienh/Sharrre/issues) for this yet (although it seems the project is no longer maintained).
- LinkedIn's share count docs are not accessible for me, so I can't see the spec for their count endpoint: https://developer.linkedin.com/docs/js-sdk/api-reference/retrieving-share-counts-for-custom-buttons

**Comment by NicktheGeek** [comment] 2016-05-12 13:46
ok, pushed a fix for this to master, develop, rainmaker-master, and rainmaker-develop. Pick your poison to test it.

**Test Scenario**: Setup the plugin to show LinkedIn

**Test Verification**: 

- [ ] Verify LinkedIn button shows
- [ ] Verify LinkedIn count shows like it did previously

**Other Features/Areas Affected**:  N/A

**Comment by NicktheGeek** [comment] 2016-05-12 15:08
ok, found a solution that works for LinkedIn to get the counts despite the API changes

**Comment by nickcernis** [comment] 2016-05-12 15:38
Thanks, Nick! Looks good in WordPress [http://debug.wpdemo.me/test-word-wrapping/ ]:

<img width="415" alt="test_word_wrapping_-_my_blog" src="https://cloud.githubusercontent.com/assets/647669/15220393/44afb3f8-185f-11e6-84a3-836b0a8c431d.png">

Have not tested Rainmaker yet.

In case the PHP count fallback causes problems for any users, an alternative fix may be to specify the  JS callback function name manually to exclude punctuation and numbers. i.e. Use `$.ajaxSetup({ jsonpCallback: "simpleShare" });` before using `$.getJSON()` in `jquery.sharrre.js` around line 490. (We have seen support issues with the PHP count method used for Google+ due to server security rules, but not very often – happy to monitor this.)

**Comment by NicktheGeek** [comment] 2016-05-12 15:51
> We have seen support issues with the PHP count method used for Google+ due to server security rules, but not very often – happy to monitor this

The issue is more than just the callback. When I removed that and tested I got a different fail error based on the domain not being allowed. It seems LinkedIn changed their security and are now blocking the JS request methods like this. Which is why I had to rewrite to use the .php file, not dealing with the callback itself.

**Comment by nickcernis** [comment] 2016-05-12 17:04
> When I removed that and tested I got a different fail error based on the domain not being allowed.

Removing the `callback=?` param altogether turns the JSONP request into a regular JSON one, I believe:

> If the URL includes the string "callback=?" (or similar, as defined by the server-side API), the request is treated as JSONP instead. See the discussion of the jsonp data type in $.ajax() for more details.
> – http://api.jquery.com/jQuery.getJSON/#jsonp

A JSON request will trigger the cross-domain error you saw because JSON requests are subject to the same-origin policy, unlike JSONP. I get the same error when pasting `jQuery.getJSON('https://www.linkedin.com/countserv/count/share?format=jsonp&url=http%3A%2F%2Fexample.com%2F', function (json) { console.log(json); });` into the console on http://www.copyblogger.com/email-marketing-defined/, for example (missing `callback` param drops the request to JSON). 

Seems crazy that LinkedIn would start validating the callback parameter name all of a sudden. Your PHP idea is really smart and looks good – thank you for jumping on this so fast.

Just waiting on RM sites to update to test it there. (I am still currently seeing LinkedIn errors on http://nick-cernis.pro01.rmkr.net/admin/admin.php?page=universal-settings&tab=traffic still.)

**Comment by NicktheGeek** [comment] 2016-05-12 17:31
The RM sites should have updated by now. Likely you have cached JS.

**Comment by nickcernis** [comment] 2016-05-12 19:13
Hmm. I used _Empty Cache and Hard Reload_ and tried two other browsers but don't see the latest JS. Guessing `http://nick-cernis.pro01.rmkr.net/` may not be updating hourly.

@katyfb13 Please could I have your help testing this fix for Rainmaker at some point?

##### Test verification:
- [ ] Check that LinkedIn button and count displays on `/admin/admin.php?page=universal-settings&tab=traffic` when LinkedIn is checked in the settings at the bottom of that page.
- [ ] Check that LinkedIn button and count shows on a post or page when set to display.

**Comment by eugenoprea** [comment] 2016-05-13 14:23
I can verify that the LinkedIn button shows on the cbmdev02 site, on the "develop" branch.

<img width="641" alt="screen shot 2016-05-13 at 17 22 06" src="https://cloud.githubusercontent.com/assets/3429948/15250860/579df634-192f-11e6-9aa5-a44e2dbf7969.png">

**Comment by NicktheGeek** [comment] 2016-05-16 13:57
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;481bLUPF&#x2F;658-update-genesis-simple-share-to-address-linkedin-api-change"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update Genesis Simple Share to address LinkedIn API change</a>

**Comment by NicktheGeek** [comment] 2016-05-16 18:05
This is deployed for WP.org as version 1.0.7

**Comment by NicktheGeek** [comment] 2017-08-22 15:03
closing as this should be in production

**Closed by NicktheGeek** 2017-08-22 15:03 UTC
Labels: QA - Confirmed 1, Type: bug
