### ISSUE TITLE
Facebook buttons all showing zero count

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-share#77] opened 2016-08-19 08:15 UTC
Facebook dropped support for their public share count REST API.

Requests now return, “REST API is deprecated for versions v2.1 and higher (12)”: https://api.facebook.com/method/links.getStats?urls=http://example.com/&format=json

<img width="644" alt="https___api_facebook_com_method_links_getstats_urls_http___example_com__format_json" src="https://cloud.githubusercontent.com/assets/647669/17802511/9baca1a8-65e8-11e6-95ca-451907eb0368.png">

All Facebook buttons on Rainmaker and WP sites now show a count of zero: http://www.copyblogger.com/email-marketing-defined/

<img width="705" alt="email_marketing_defined_in_60_seconds__animated_video__-_copyblogger_-" src="https://cloud.githubusercontent.com/assets/647669/17802616/2375d2bc-65e9-11e6-8928-2c5cdd8a5a79.png">

I found that counts are still available via the Graph API, seemingly without authentication:

- https://graph.facebook.com/?id=http://example.com
- https://graph.facebook.com/?ids=http://example.com,https://example.com

<img width="1191" alt="https___graph_facebook_com__id_http___example_com" src="https://cloud.githubusercontent.com/assets/647669/17803167/9aa8fb04-65ec-11e6-8a2d-222fcb3475de.png">

This is the same endpoint Automattic are using in Jetpack at the moment: https://github.com/Automattic/jetpack/blob/5302991caad01efd2b91977b711c525fd65191f7/modules/sharedaddy/sharing.js#L36

They were already using the graph API, but are updating their plugin to reference the new object structure: https://github.com/Automattic/jetpack/pull/4879

Authentication appears to be required only if you specify an API version:

- https://graph.facebook.com/v2.7/?id=http://example.com
- https://developers.facebook.com/docs/graph-api/reference/v2.7/url

Suggest we either use the new Graph API endpoint while it's available (preferred) or drop the Facebook count.

### Further info

Thanks to @eugenoprea for the heads-up on this and for digging up some industry chatter:

- http://www.sharedcount.com/notes/facebook_api_shutdown.php
- https://wordpress.org/support/topic/facebook-share-counts-not-showing#post-8772744
- http://www.inc.com/james-parsons/the-era-of-the-share-count-is-coming-to-an-end.html

**Comment by NicktheGeek** [comment] 2016-08-19 15:38
**Test Scenario**: 

- check a post that has been shared on FB or share a post on FB to verify the count

**Test Verification**: 

- [ ] Verify share count continues to work.

**Comment by katyfb13** [comment] 2016-08-19 15:46
@NicktheGeek so where is this to be tested?

**Comment by NicktheGeek** [comment] 2016-08-19 16:13
We can verify it in dev02 using the issue for Rainmaker, that will be enough to verify it for release on this plugin. Assuming we can do that we can push the plugin update Monday.

**Comment by katyfb13** [comment] 2016-08-19 16:47
This was confirmed in dev02. If you need me to upload a revised plugin to a wp install, please let me know.

![screen shot 2016-08-19 at 11 44 53 am](https://cloud.githubusercontent.com/assets/2847436/17817135/82a3ab92-6602-11e6-94cc-f31eb6d7af04.png)

Sounds like this is production ready pending possible plugin testing.

**Comment by billerickson** [comment] 2016-08-19 19:22
You might want to check on this for higher traffic sites. 

I recently updated [EA Share Count](https://github.com/jaredatch/ea-share-count) since SharedCount.com shut down, and found that sometimes the unauthenticated API requests worked (like on my local environment, or from a browser), but in production they didn't work (e.g., on billerickson.net). 

I think if you don't provide an API key they use some other means of identifying you, like an IP address, and still limit the number of queries. 

I had to create a long-lived Facebook Access Token for the counts to work again.

**Comment by NicktheGeek** [comment] 2016-08-19 19:29
@billerickson Thanks, we'll get some info when we run the update on copyblogger.com.

We've got a different service that handles twitter share there, but we may need something like that for FB share. 

It's great how these social services are crippling features that people use that drive traffic for their service. It's like FB saw the death spiral of Twitter and though, "man, that's pretty sweet. I need to get me a piece of that action."

**Comment by billerickson** [comment] 2016-08-19 19:35
What probably helps you is you're doing it via Javascript, so it's tied to the visitor's IP. We do it server-side so it's tied to our IP.

Yeah, it's definitely annoying how difficult the social services make this. But I'm not surprised Facebook is moving to requiring access tokens. It's the first step in them charging for access to the API, like they charge businesses who want to share their Facebook posts with people already following those businesses.

**Comment by guidedmathadventures** [comment] 2016-08-20 14:47
I am trying to fix this problem on my wp site and have tried to follow the comments here.  Will this plugin be fixed so facebook shares no longer show zero, or is there a way I can fix it myself.  Thanks for your help!

**Comment by nickcernis** [comment] 2016-08-20 15:10
@guidedmathadventures Thanks for checking in! Yes, you'll see a plugin update next week to fix the Facebook counts. :-) Sorry for the inconvenience in the meantime.

**Comment by NicktheGeek** [comment] 2016-08-20 16:05
Anyone wishing to test this fix can download the develop branch from this git repo and replace their plugin with the provided file. 

The update should go out Monday unless something comes up.

**Comment by billerickson** [comment] 2016-08-20 18:23
Here's the direct link to the download: https://github.com/copyblogger/genesis-simple-share/archive/develop.zip

**Comment by bgardner** [comment] 2016-08-20 19:21
I just pushed the plugin up on No Sidebar, and it appears to be showing the FB counts:

http://nosidebar.com/things-minimalists-dont-do/

**Closed** 2016-08-22 20:07 UTC
Labels: Priority 1, QA - Confirmed 1, QA: 5 - in production, Support: Priority 1, Type: bug
