### ISSUE TITLE
Can we have a option to display counts or not

### ISSUE THREAD

**Issue by calliaweb** [copyblogger/genesis-simple-share#59] opened 2015-10-01 09:46 UTC
With Twitter removing counts, could we have the option to just not display any counts?

I have a client who doesn't want to show the counts so I "fixed" it by display:none on the .count link. This of course now doesn't work on the Twitter button and I'm left with the word Tweet.

I'm working on a fudge (by fixing the width of the new .no-count element) but wondered if having the option to remove all the counts would be useful to other too?

Cheers
Jo

**Comment by nickcernis** [comment] 2015-10-04 20:24
Just noting that another user would also like to show the share verbs (“share”, “like” etc.) instead of showing the counts, particularly when share counts are zero for a post: https://wordpress.org/support/topic/prospective-solution-for-the-twitter-issue?replies=2#post-7503632

**Comment by dreamwhisper** [comment] 2015-11-24 14:30
Getting quite a few requests for this through support as well.

**Comment by NicktheGeek** [comment] 2015-11-25 16:52
This is actually a duplicate of #8

**Closed by NicktheGeek** 2015-11-25 16:52 UTC
Labels: Type: duplicate
