### ISSUE TITLE
Twitter no longer offering share count endpoints

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-share#58] opened 2015-09-23 11:25 UTC
Twitter are dropping support for share count retrieval in October 2015:

> The Tweet button has displayed share count over the last five years by querying a JSON endpoint hosted on various domains. These private JSON endpoints have been used by third-party developers over the years to retrieve a simple share count of any URL. **These endpoints will be shut down next month when the Tweet button removes its share count feature.**

– Source: [twitter dev forums](https://twittercommunity.com/t/a-new-design-for-tweet-and-follow-buttons/52791)

The Sharrre library currently uses one of the endpoints that will presumably be removed: `http://cdn.api.twitter.com/1/urls/count.json?url={url}&callback=?` ([source](https://github.com/Julienh/Sharrre/blob/master/jquery.sharrre.js#L108)).

If Sharrre is not updated to work around this (it no longer seems to be actively maintained), twitter counts will stop working in October.

It may be worth removing the share count feature for the twitter button before then.

**Comment by NicktheGeek** [comment] 2015-09-23 11:28
Twitter: People like using our service but we don't know why. Let's try to resolve the problem. Oh, no we don't want to understand why people like it. We want to resolve the part about them liking it. That seems like the simpler approach.

**Comment by bgardner** [comment] 2015-09-23 11:31
I'm suspecting support will need to have a snippet ready, because no doubt we'll get flooded with "your plugin doesn't work as my tweet count isn't showing" emails.

**Comment by katyfb13** [comment] 2015-09-23 14:42
Isn't this used in Rainmaker?

**Comment by NicktheGeek** [comment] 2015-09-23 14:48
yes, we'll have to do an update of this in RM. I'm looking at various options on how to handle this because I know the count going away is going to irritate a lot of people.

**Comment by bgardner** [comment] 2015-09-23 14:55
Thankfully we can blame Twitter, rather than it being our plugin/functionality isn't working.

**Comment by bgardner** [comment] 2015-09-23 14:55
And can I add how much of a stupid idea I think it is that they are doing away with numbers.

**Comment by NicktheGeek** [comment] 2015-09-23 15:06
> And can I add how much of a stupid idea I think it is that they are doing away with numbers.

Plus a million on that

**Comment by katyfb13** [comment] 2015-09-23 19:47
@NicktheGeek  from a timing perspective, do you think we should get this in 2.3.4 (which looks like it will go out 10/7 at this point) ... if we can? Or do you think we will need to do a quick patch to push out a fix for this separate from a milestone?

**Comment by katyfb13** [comment] 2015-09-23 20:09
putting this in 2.3.4 and if we miss that then we can put out a quick patch when ready

**Comment by NicktheGeek** [comment] 2015-09-24 19:44
**Test Branch**: Master (test in hourly for RM)

**Test Scenario**: This disables the twitter count. Make sure the Twitter share button is enabled.

**Test Verification**: 

- [ ] Verify twitter share button shows without the count
- [ ] Verify the button still allows share

**Other Features/Areas Affected**:  N/A

**Comment by katyfb13** [comment] 2015-09-24 22:56
This passes in terms of not showing the count and continuing to post to Twitter.

![screen shot 2015-09-24 at 5 51 04 pm](https://cloud.githubusercontent.com/assets/2847436/10089088/7b1dcefa-62e5-11e5-8ab1-f5489af89bbe.png)


However, when you select the large box design, it looks really odd. 

![screen shot 2015-09-24 at 5 51 29 pm](https://cloud.githubusercontent.com/assets/2847436/10089082/71bba3aa-62e5-11e5-9448-a9db789840d9.png)

Perhaps @rafaltomal can take a look and make a suggestion?

**Comment by rafaltomal** [comment] 2015-09-25 06:10
Ok, this is the best design solution I could come up with:

**Comment by NicktheGeek** [comment] 2015-09-25 11:24
@rafaltomal wow, I'll be honest, I didn't think it would be possible to come up with something elegant but this is perfect.

**Comment by katyfb13** [comment] 2015-09-25 15:55
> wow, I'll be honest, I didn't think it would be possible to come up with something elegant but this is perfect.

I agree 1000%! This is sheer genius.

@rafaltomal I did find a couple of iddy bitty issue though. In chrome and firefox the background of it is transparent
![screen shot 2015-09-25 at 9 02 37 am](https://cloud.githubusercontent.com/assets/2847436/10105313/a50b3ea8-6373-11e5-8ddb-017b74f5a87a.png)

And in Safari, in addition to the transparency, it does not line up with the others (I am on a Mac)

![screen shot 2015-09-25 at 9 10 21 am](https://cloud.githubusercontent.com/assets/2847436/10105300/8974f260-6373-11e5-994d-957c1e594528.png)

**Comment by rafaltomal** [comment] 2015-09-25 16:59
Ok, @katyfb13 that one was tricky... Safari never liked me.

It's ready for testing. Please test it on a couple different themes too just to make sure and icons both before and after the content. If it works on 2-3 themes, then it should be good on all of them.

**Comment by katyfb13** [comment] 2015-09-25 18:47
@rafaltomal @NicktheGeek this is not fixed yet and the sync should have gone through by now. Can someone check it see why that may not be going through please?

**Comment by katyfb13** [comment] 2015-09-25 18:49
and it's not working in cbmpackag01 either

![screen shot 2015-09-25 at 1 48 44 pm](https://cloud.githubusercontent.com/assets/2847436/10109385/320f39d6-638c-11e5-8caa-87ac1dfdfb4b.png)

**Comment by NicktheGeek** [comment] 2015-09-25 18:49
@katyfb13 sorry, looks like the code was committed to develop. I merged to master. It should be there after the next hourly update.

**Comment by katyfb13** [comment] 2015-09-25 18:50
okay thanks @NicktheGeek

**Comment by katyfb13** [comment] 2015-09-25 21:03
this is confirmed and regression ready.

I tested this with Rainmaker, Streamline, Agency and Parallax. All look good.

**Comment by nickcernis** [comment] 2015-09-28 13:29
Love the design solution, @rafaltomal! Many thanks for the fix and for testing, @NicktheGeek and @katyfb13.

Just noting that Twitter appear to have shut down the count endpoints early, as the twitter button is no longer loading for some users or for my RM preview site.

This is affecting RM admin pages at `/admin/admin.php?page=universal-settings&tab=traffic` (which now fail to load for me after spinning for two minutes):

![universal_settings_ _test_site_ _rainmaker](https://cloud.githubusercontent.com/assets/647669/10136184/146d091a-65eb-11e5-81b5-8366efd94228.jpg)

We've also had [one report](https://wordpress.org/support/topic/problems-with-twitter-share-button?replies=1#post-7479150) in the WP.org forums that the tweet count no longer loads, and that it prevents the rest of the page loading for this particular user. (Disabling the twitter button resolves this.)

The [Copyblogger](http://www.copyblogger.com/blog) and [StudioPress](http://www.studiopress.com/blog) blogs don't seem to be affected yet, though.

Just wanted to mention it in case the WP plugin or RM can be updated earlier than planned. (No big deal if not; I will just let folks know that a fix is in the pipeline.)

**Comment by nathanrice** [comment] 2015-09-28 17:58
I'm pushing out updates to plugins this week, so I'll go ahead and tag/release this one.

**Comment by NicktheGeek** [comment] 2015-09-28 18:04
> I'm pushing out updates to plugins this week, so I'll go ahead and tag/release this one.

@nathanrice thanks!

**Comment by rafaltomal** [comment] 2015-10-02 18:54
Ok, I have a small problem with this new Twitter button.. especially in all of our landing pages. I think we need to take a step back and change it's HTML code.

@NicktheGeek This is what is right now:

```
<div class="box no-count">
<a class="share" href="#">Tweet</a>
</div>
```

... and I would prefer we change it to this:

```
<div class="box">
<a href="#" class="count"></a>
<a class="share" href="#">Tweet</a>
</div>
```

I know, it's an empty tag, but it'll be easier to manage. Once you make this change, I'll need to redo my styling and then we'll need to test it all again. Sorry, but I didn't predict how it'll affect the social buttons on landing pages...

**Comment by NicktheGeek** [comment] 2015-10-02 19:11
@rafaltomal I went ahead and added `<a href="#" class="count"></a>` to the markup but left the `co-count` class. This is in `rainmaker-develop` so it can be tested on the dev01 and dev02 servers. There is a pull request to `rainmaker-master` so if you need it in the package/hourly servers you can approve the pull request to merge it.

**Comment by rafaltomal** [comment] 2015-10-02 21:19
It's ready for testing. It should look and work same as previously:

![image](https://cloud.githubusercontent.com/assets/4073247/10258083/465db27e-6921-11e5-9270-578c70fe246f.png)

Let's just make sure it works. I'm updating the landing pages now, which should be much easier :)

Thanks @NicktheGeek!

**Comment by susannelson** [comment] 2015-10-08 10:37
@katyfb13 For some reason, I cannot adjust the labels on this issue. Can you please remove the "needs docs" and "UI change" labels and add "docs complete"? Thanks!

**Comment by eugenoprea** [comment] 2015-10-09 19:33
Confirmed and production ready!

**Comment by brugeman** [comment] 2015-10-27 04:29
Hi guys! 
I'm building a free service to track twitter shares and provide a public API that serves share counts. It could be integrated with your plugin and provide your customers with Twitter share counts they got used to. 
If you're interested, drop me a line to brugeman.artur at gmail.com.

**Closed** 2015-10-27 19:48 UTC
Labels: Docs: complete, QA - 2 package ready, Type: enhancement, Type: newsworthy
